name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 0.2.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics.firebasecrashlytics
        pluginClass: FirebaseCrashlyticsPlugin
      ios:
        pluginClass: FirebaseCrashlyticsPlugin
      macos:
        pluginClass: FirebaseCrashlyticsPlugin

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.9.3
  firebase_core: ">=0.5.0-dev.1 <0.6.0"
  firebase_core_platform_interface: ">=2.0.0-dev.1 <2.1.0"
  firebase_crashlytics_platform_interface:
    path: ../firebase_crashlytics_platform_interface

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.4.3+1
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"