name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  google_sign_in: ^4.0.0
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links
  uuid: ^2.0.2

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
