name: firebase_storage

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - "packages/firebase_storage/**"
      - ".github/workflows/firebase_storage.yaml"
  push:
    branches:
      - master

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_storage*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*firebase_storage_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build apk
      - name: Download Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-28;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name TestingAVD --device "Nexus 5X" -k 'system-images;android-28;google_apis;x86_64' -g google_apis
          $ANDROID_HOME/emulator/emulator -list-avds
      - name: Start Android Emulator
        timeout-minutes: 15
        continue-on-error: true
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd TestingAVD -no-audio -no-snapshot -no-window -no-boot-anim &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done'
          $ANDROID_HOME/platform-tools/adb devices
          $ANDROID_HOME/platform-tools/adb shell settings put global window_animation_scale 0.0
          $ANDROID_HOME/platform-tools/adb shell settings put global transition_animation_scale 0.0
          $ANDROID_HOME/platform-tools/adb shell settings put global animator_duration_scale 0.0
          echo "Emulator started"
          flutter emulators
      - name: "Drive Example"
        run: |
          melos exec -c 1 --fail-fast --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=test_driver -- \
            flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart

  apple:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - name: "Install Tools"
        run: |
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
          flutter config --enable-macos-desktop
          flutter devices
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build iOS Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build ios --no-codesign
      - name: "Boot Simulator"
        run: xcrun simctl boot "iPhone 11"
      - name: "Drive iOS Example"
        run: |
          melos exec -c 1 --fail-fast --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=test_driver -- \
            flutter drive -d \"iPhone 11\" --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
      - name: "Shutdown Simulator"
        run: xcrun simctl shutdown "iPhone 11"
      - name: "Build MacOS Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build macos
      - name: "Drive MacOS Example"
        run: |
          melos exec -c 1 --fail-fast --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=test_driver -- \
            flutter drive -d macos --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
